name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install Dependencies 🔧
        run: npm install

      - name: Force Build Web Site 🚀
        run: NITRO_PRESET=github-pages npm run build

      - name: Copy to Dist for Deployment 📂
        # 生成された .output/public を、デプロイアクションが欲しがっている dist に丸ごとコピーします
        run: cp -r .output/public dist

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
