name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install Dependencies 🔧
        run: npm install

      - name: Project SPA Static Build 🚀
        # Nitroではなく、Vinxi全体のビルドターゲットを静的（static）に強制します
        env:
          VINXI_SERVER_PRESET: static
          NITRO_PRESET: static
        run: npm run build

      - name: Upload Artifact 📦
        # 静的SPAとして出力される一般的なディレクトリを指定します
        # もしこれでまた出力先が変わる場合は、直前のログで書き出された場所を追います
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.output/public'

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
